trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  location: $(location)
  AppInsights: $(AppInsights)
  subscription_id: $(subscription_id)
  environment_name: $(environment_name)
  client_name: $(client_name)
  resource_group_name: $(resource_group_name)
  idn_tenant_id: $(idn_tenant_id)
  env_code: $(env_code)
  serviceconn_name: $(serviceconn_name)
  backend_resource_group: $(backend_resource_group)
  backend_storage_account: $(backend_storage_account)
  backend_container_name: $(backend_container_name)
  backend_tfstate_file_name: $(backend_tfstate_file_name)

stages:           
  - stage: 
    displayName: "Deploying Terraform Resources"
 
    jobs:
      - job: 
        timeoutInMinutes: 180
        steps:
          - task: replacetokens@5
            displayName: preparing_terraform.tfvars_and_main.tf
            inputs:
                targetFiles: | 
                  **/terraform.tfvars
                  **/main.tf
                encoding: 'auto'
                tokenPattern: 'custom'
                tokenPrefix: '#{'
                tokenSuffix: '}#'
                writeBOM: true
                verbosity: 'detailed'
                actionOnMissing: 'warn'
                keepToken: false
                actionOnNoFiles: 'continue'
                enableTransforms: false
                enableRecursion: false
                useLegacyPattern: false
                enableTelemetry: true

          - task: PowerShell@2
            displayName: 'Display Terraform.tfvars File' 
            enabled: true
            inputs:
                targetType: 'inline'
                script: |
                    get-content $(build.sourcesdirectory)/terraform.tfvars     

          - task: PowerShell@2
            displayName: 'Display main.tf File' 
            enabled: true
            inputs:
                targetType: 'inline'
                script: |
                    get-content $(build.sourcesdirectory)/main.tf   

          - task: TerraformCLI@0
            displayName: "terraform init"
            enabled: true
            inputs:
              command: "init"
              backendServiceArm: $(serviceconn_name)
              backendType: "azurerm"
              backendAzureRmResourceGroupName: $(backend_resource_group)
              backendAzureRmStorageAccountName: $(backend_storage_account)
              backendAzureRmContainerName: $(backend_container_name)
              backendAzureRmKey: $(backend_tfstate_file_name)
              allowTelemetryCollection: true
              workingDirectory: $(System.DefaultWorkingDirectory)

          - task: TerraformCLI@0
            displayName: "terraform plan"
            enabled: true
            inputs:
              command: 'plan'
              workingDirectory: $(System.DefaultWorkingDirectory)
              environmentServiceName: $(serviceconn_name)
              commandOptions: '--out=tfplan'
              allowTelemetryCollection: true
                      
          - task: TerraformCLI@0
            displayName: "terraform apply"
            enabled: true  
            inputs:
              command: 'apply'
              workingDirectory: $(System.DefaultWorkingDirectory)
              environmentServiceName: $(serviceconn_name)
              commandOptions: 'tfplan'
              allowTelemetryCollection: true
            condition: and(succeeded(), eq(variables['TerraformApply'], 'True'))

          - task: TerraformCLI@0
            displayName: "terraform destroy"
            enabled: true
            inputs:
              command: 'destroy'
              workingDirectory: $(System.DefaultWorkingDirectory)
              environmentServiceName: $(serviceconn_name)
              allowTelemetryCollection: true
            condition: and(succeeded(), eq(variables['TerraformDestroy'], 'True'))