trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  location: 'eastus'
  AppInsights: 'poh-4-f8c75af9-d48f-4600-9db9-00d1325b865a-client1-dev-ai'
  subscription_id: '2daf7420-f7f4-4e0f-8a65-8dd8f147545b'
  environment_name: 'dev'
  client_name: 'client1'
  resource_group_name: 'POH'
  idn_tenant_id: 'f8c75af9-d48f-4600-9db9-00d1325b865a'
  env_code: '4'
  serviceconn_name: 'AzureConnection'
  backend_resource_group: 'POH'
  backend_storage_account: 'tfstorageac15'
  backend_container_name: 'terraform'
  backend_tfstate_file_name: 'terraform.tfstate'

stages:           
  - stage: 
    displayName: "Deploying Terraform Resources"
    
    jobs:
      - job: 
        timeoutInMinutes: 180
        steps:
          - task: replacetokens@5
            displayName: preparing_terraform.tfvars_and_main.tf
            inputs:
                targetFiles: | 
                  **/*.tfvars
                  **/*.tf
                encoding: 'auto'
                tokenPattern: 'custom'
                tokenPrefix: '#{'
                tokenSuffix: '}#'
                writeBOM: true
                verbosity: 'detailed'
                actionOnMissing: 'warn'
                keepToken: false
                actionOnNoFiles: 'continue'
                enableTransforms: false
                enableRecursion: false
                useLegacyPattern: false
                enableTelemetry: true

          - task: PowerShell@2
            displayName: 'Display Terraform.tfvars File' 
            enabled: true
            inputs:
                targetType: 'inline'
                script: |
                    get-content $(build.sourcesdirectory)/terraform.tfvars     

            
