parameters:
- name: azureSubscriptionId
  type: string
  default: '2daf7420-f7f4-4e0f-8a65-8dd8f147545b'
variables:
  location: 'East US 2'
  resourcegroupname: 'POH'
  terraformstorageaccount: 'My'
  terraformstoragerg: 'POH'
  subscription: ${{ parameters.azureSubscriptionId }}

stages:
  - stage: 
    displayName: "Preparing terraform.tfvars"
    
    jobs:
      - job:
       
        steps:
          - task: replacetokens@5
            displayName: 'Replace tokens in terraform files **/*.tfvars'
            inputs:
              targetFiles: '**/*.tfvars'
              escapeType: none
              tokenPrefix: '__'
              tokenSuffix: '__'

          - template: ../../../../templates/terraform-deploy.yml
            parameters:
              working_dir: "$(Build.SourcesDirectory)/terraform/environments/nonprod/envgroup"
              serviceconn_name : $(Azure_Service_Connection)
              tfresourcegroupname : $(Shared_Resource_Group)
              tfstorageaccountname : $(TfState_StorageAccount)
              azureRmContainerName : $(TfState_StorageContainer)
              tfstatefile : "poh-${{ variables.environment}}-${{ variables.environment_resource_group }}.tfstate"