location             = "#{location}#"
AppInsights          = "#{AppInsights}#"
environment_name     = "#{environment_name}#"
client_name          = "#{client_name}#"
resource_group_name  = "#{resource_group_name}#"
idn_tenant_id        = "#{idn_tenant_id}#"
env_code             = "#{env_code}#"
DashboardRG          = "#{DashboardRG}#"
